server:
  port: 2333
  address: localhost
lavalink:
  plugins:
  - dependency: "dev.lavalink.youtube:youtube-plugin:1.5.1"
    snapshot: false 
    youtube:
      enable: true
      allowSearch: true
      allowDirectVideoIds: true
      allowDirectPlaylistIds: true
      clients:
        - MUSIC
        - ANDROID_TESTSUITE
        - WEB
        - TVHTML5EMBEDDED
  server:
    password: "myveryhardpassword"
    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: false
      vimeo: false
      mixer: false
      http: true
  pluginsPath: ./plugins
