server:
  port: 2333
  address: localhost
lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.8.3"
      snapshot: false
      youtube:
        enable: true
        allowSearch: true
        allowDirectVideoIds: true
        allowDirectPlaylistIds: true
        clients:
          - WEB
          - MUSIC
          - TVHTML5EMBEDDED
          - ANDROID_MUSIC
          - WEBEMBEDDED
          - ANDROID
          - ANDROID_LITE
          - MEDIA_CONNECT
          - IOS
  server:
    password: "myveryhardpassword"
    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: false
      vimeo: false
      mixer: false
      http: true
  pluginsPath: ./plugins
