plugins:
  lavasrc:
    providers:
      - "ymrec:\"%ISRC%\""
      - "ymsearch:%QUERY%"
    sources:
      youtube: false
      yandexmusic: true
    yandexmusic:
      accessToken: "токен_яндекс_музыки"
      playlistLoadLimit: 1
      albumLoadLimit: 1
      artistLoadLimit: 1

server:
  port: 2333
  address: localhost
lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.3.0"
      snapshot: false
  server:
    password: "пароль_вашего_лавалинка"
    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: false
      vimeo: false
      mixer: false
      http: true
  pluginsPath: ./plugins