name: Docker Image CI main branch

on:
  release:
    types: [published]
  # push:
  #   branches: [ "refactor/show-waifus-command" ]
  #   paths-ignore:
  #     - '.dockerignore'
  #     - '.flake8'
  #     - '.gitignore'
  #     - 'LICENSE.md'
  #     - 'README.md'
  #     - 'README.ru.md'
  #     - 'requirements.txt'

jobs:
  push:
    name: Push it stronger
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_EMAIL }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: vmstr8/discord-music-bot
      #     tags: |
      #       type=sha,enable=true,priority=100,prefix=foot-,suffix=-fetish,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          platforms: |-
            linux/amd64
            linux/arm64
          no-cache: true
          tags: ${{ env.GITHUB_REF }}
          labels: ${{ steps.meta.outputs.labels }}
